version: '3'

services:
    db:
        image: mysql:5.7
        volumes:
          - .data/:/var/lib/mysql
        restart: always
        ports:
          - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
            MYSQL_DATABASE: "${DATABASE_NAME}"
            MYSQL_USER: "${DATABASE_USERNAME}"
            MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
    phpmyadmin:
        depends_on:
          - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
          - '7000:80'
        environment:
          PMA_HOST: db
          MYSQL_ROOT_PASSWORD: demo